#if !canImport(ObjectiveC)
import XCTest

extension IntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntTests = [
        ("testIntFromStringDefaultValue", testIntFromStringDefaultValue),
    ]
}

extension SequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SequenceTests = [
        ("testSortByKeyPath", testSortByKeyPath),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testNilOrEmpty", testNilOrEmpty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IntTests.__allTests__IntTests),
        testCase(SequenceTests.__allTests__SequenceTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
