#if !canImport(ObjectiveC)
import XCTest

extension CharacterSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CharacterSetTests = [
        ("testRFC3986Unreserved", testRFC3986Unreserved),
    ]
}

extension IntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntTests = [
        ("testIntFromStringDefaultValue", testIntFromStringDefaultValue),
    ]
}

extension SequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SequenceTests = [
        ("testSortByKeyPath", testSortByKeyPath),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testFromBase64String", testFromBase64String),
        ("testHexStringToByteArray", testHexStringToByteArray),
        ("testIsValidHexNumber", testIsValidHexNumber),
        ("testNilOrEmpty", testNilOrEmpty),
        ("testToBase64String", testToBase64String),
        ("testToISO8601Date", testToISO8601Date),
        ("testTruncated", testTruncated),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CharacterSetTests.__allTests__CharacterSetTests),
        testCase(IntTests.__allTests__IntTests),
        testCase(SequenceTests.__allTests__SequenceTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
